[build]
  command = "echo 'Building...'"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# 정적 파일 우선 처리 (CSS, JS, 이미지 등)
[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
  force = true

[[redirects]]
  from = "/script.js"
  to = "/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/nav.js"
  to = "/nav.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# CMS 관리자 페이지
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# 서브 페이지들
[[redirects]]
  from = "/about/*"
  to = "/about/:splat.html"
  status = 200

[[redirects]]
  from = "/news/*"
  to = "/news/:splat.html"
  status = 200

[[redirects]]
  from = "/resources/*"
  to = "/resources/:splat.html"
  status = 200

# 메인 페이지들
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/policy"
  to = "/policy.html"
  status = 200

[[redirects]]
  from = "/news"
  to = "/news.html"
  status = 200

[[redirects]]
  from = "/members"
  to = "/members.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

# 404 처리
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 보안 헤더
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"

# 정적 자산 캐싱
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/javascript" 