[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm start"

# Volume 설정 - uploads 디렉토리를 영구 저장소로 마운트
[volumes]
uploads = "/app/uploads"

# 환경변수 설정
[environments.production.variables]
UPLOADS_PATH = "/app/uploads"
NODE_ENV = "production" 