name: Sync CMS Data to HTML (DISABLED)

on:
  # 임시로 모든 트리거 비활성화
  workflow_dispatch:
    inputs:
      force_run:
        description: '강제 실행'
        required: false
        default: 'false'

# 기존 트리거들을 주석 처리
#  push:
#    paths:
#      - 'content/homepage.yml'
#      - 'content/**'

permissions:
  contents: write
  actions: read

jobs:
  # 임시로 스킵
  skip-sync:
    name: CMS 동기화 스킵
    runs-on: ubuntu-latest
    steps:
      - name: 알림
        run: |
          echo "⚠️ CMS 데이터 동기화가 임시로 비활성화되었습니다"
          echo "📝 JavaScript 기반 동적 로딩으로 전환되었습니다" 