party_name: "자유와혁신"
slogan: "새로운 대한민국을 함께 만들어 갑니다"
main_phone: "02-1234-5678"
main_email: "info@jayuhyeoksin.kr"
address: "서울특별시 중구 세종대로 1가 31 정동빌딩 7층"
social_media:
  facebook: "https://facebook.com/jayuhyeoksin"
  twitter: "https://twitter.com/jayuhyeoksin"
  instagram: "https://instagram.com/jayuhyeoksin"
  youtube: "https://youtube.com/c/jayuhyeoksin"
membership_url: "https://forthefreedom.vercel.app/members/join.html"
donation_url: "https://forthefreedom.vercel.app/support.html" 