name: CMS Content Logging & Archive (DISABLED)

on:
  # 임시로 모든 트리거 비활성화
  workflow_dispatch:
    inputs:
      force_run:
        description: '강제 실행'
        required: false
        default: 'false'

# 기존 트리거들을 주석 처리
#  push:
#    paths:
#      - 'content/**'
#      - 'about/**'
#      - 'policy/**'
#      - 'news/**'
#      - 'members/**'
#      - 'resources/**'
#      - 'notices/**'
#      - 'index.html'
#      - 'images/**'
#      - 'style.css'
#      - 'script.js'

jobs:
  # 임시로 스킵
  skip-logging:
    name: CMS 로깅 스킵
    runs-on: ubuntu-latest
    steps:
      - name: 알림
        run: |
          echo "⚠️ CMS 로깅이 임시로 비활성화되었습니다"
          echo "📝 JavaScript 기반 시스템으로 전환되었습니다" 